#!/usr/bin/env bash
# Concatenate the migrations into one file for the Supabase SQL editor.
#
# The CLI (`supabase link` + `supabase db push`) is the better path: it records
# what has been applied, so the next migration knows where to start. This is for
# the first run on a fresh project, where there is nothing to track yet and
# where the CLI wants an access token and a database password that are awkward
# to produce.
#
# Generated on demand rather than committed, so it cannot drift from the
# migrations it is built from.
#
#   ./supabase/bundle.sh > /tmp/schema.sql
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cat <<'HEADER'
-- ---------------------------------------------------------------------------
-- Talibalim — full schema, for a FRESH Supabase project.
--
-- Generated by supabase/bundle.sh from supabase/migrations/, in filename
-- order. Paste the whole thing into the Supabase SQL editor and run it once.
--
-- PURE SQL ONLY. No psql meta-commands (\echo, \set, \i) and no explicit
-- BEGIN/COMMIT: the Supabase SQL editor is not psql, it rejects backslash
-- commands outright, and it already runs the whole paste inside one
-- transaction of its own. A single unrecognised line there rolls back
-- everything, which looks exactly like nothing happened.
--
-- Run this ONCE. It creates types and tables, so a second run fails on the
-- first `create type` — the safe failure. After this, use `supabase db push`.
-- ---------------------------------------------------------------------------

HEADER

for file in "$here"/migrations/*.sql; do
  printf -- '-- ===========================================================================\n'
  printf -- '-- %s\n' "$(basename "$file")"
  printf -- '-- ===========================================================================\n\n'
  cat "$file"
  printf '\n\n'
done

cat <<'FOOTER'
-- Ran without error? Confirm with:
--   select count(*) from information_schema.tables where table_schema = 'public';
-- It should be 17.
FOOTER
