#!/usr/bin/env bash
# Build ONE re-runnable script that brings an existing project up to date.
#
# `bundle.sh` is for a fresh project and fails on a second run — deliberately,
# because `create type` refusing is the safe way to stop somebody re-running a
# whole schema. That safety is useless once a project is live and the question
# becomes "which of these twenty-one files did I already run?", which is not a
# question anybody can answer by looking. Getting it wrong costs an afternoon;
# the coupon generator was missing for days because of exactly this.
#
# So this rewrites the migrations to be idempotent and concatenates them:
#
#   create table X            -> create table if not exists X
#   create index X            -> create index if not exists X
#   create policy X on T      -> drop policy if exists X on T; create policy ...
#   create trigger X on T     -> drop trigger if exists X on T; create trigger ...
#   add column X              -> add column if not exists X
#
# That last one is not hypothetical: a second run failed on
# `add column require_approval` in 20260913100000 until it was guarded. Which is
# the entire argument for testing this script against a real database rather
# than reading it and deciding it looks right.
#
# `create or replace function`, `add column if not exists` and `enable row level
# security` are already safe to repeat, and the migrations in range use guarded
# `do $$ ... end $$` blocks for constraints.
#
# Run it as many times as you like. It ends by reloading PostgREST's schema
# cache and printing what is actually present, so the answer is on screen rather
# than inferred from whether the app stopped complaining.
#
#   ./supabase/catchup.sh > /tmp/catchup.sql     (or: npm run db:catchup)
#
# Paste the result into the Supabase SQL editor and run it.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Everything from the coupon fix onwards. Earlier files create types and tables
# that every live project already has, and rewriting those to be idempotent
# would be a lot of machinery for no gain.
FROM="20260912160000"

cat <<'HEADER'
-- ---------------------------------------------------------------------------
-- Talibalim — catch-up script for an EXISTING Supabase project.
--
-- Generated by supabase/catchup.sh. Safe to run as many times as you want:
-- everything in here either creates something missing or replaces it with the
-- same definition. It will not touch a single row of your data.
--
-- Paste the whole thing into the Supabase SQL editor and press Run.
--
-- PURE SQL ONLY — no psql backslash commands. The Supabase editor is not psql
-- and runs the whole paste in one transaction, so one unrecognised line rolls
-- the lot back and looks exactly like nothing happened.
--
-- The last statement prints what is present. Read it. If a row says MISSING,
-- the paste did not do what it says it did.
-- ---------------------------------------------------------------------------

HEADER

for file in "$here"/migrations/*.sql; do
  name="$(basename "$file")"
  [[ "${name%%_*}" < "$FROM" ]] && continue

  printf -- '-- ===========================================================================\n'
  printf -- '-- %s\n' "$name"
  printf -- '-- ===========================================================================\n\n'

  # The rewrites. `create policy`/`create trigger` have no IF NOT EXISTS in
  # Postgres, so they are preceded by a DROP instead — which is why the table
  # name has to be pulled out of the statement.
  awk '
    # create policy NAME on TABLE   (possibly split across lines)
    /^create policy [a-z0-9_]+ on [a-z0-9_.]+/ {
      pol = $3; tbl = $5;
      sub(/;$/, "", tbl);
      printf "drop policy if exists %s on %s;\n", pol, tbl;
      print; next;
    }
    # create trigger NAME  — the table is on a LATER line, so the statement is
    # buffered until it is known, then the drop is emitted ahead of both.
    /^create trigger [a-z0-9_]+/ { trg = $3; buf = $0; pending_trigger = 1; next; }
    pending_trigger {
      buf = buf "\n" $0;
      for (i = 1; i < NF; i++) if ($i == "on") { t = $(i+1); sub(/;$/, "", t); found = 1 }
      if (found) {
        printf "drop trigger if exists %s on %s;\n%s\n", trg, t, buf;
        pending_trigger = 0; found = 0;
      }
      next;
    }
    { print }
  ' "$file" \
    | sed -E \
      -e 's/^create table (public\.)/create table if not exists \1/' \
      -e 's/^create index (if not exists )?([a-z0-9_]+)/create index if not exists \2/' \
      -e 's/^create unique index (if not exists )?([a-z0-9_]+)/create unique index if not exists \2/' \
      -e 's/^([[:space:]]*)add column (if not exists )?([a-z])/\1add column if not exists \3/'

  printf '\n\n'
done

cat <<'FOOTER'

-- ---------------------------------------------------------------------------
-- Tell PostgREST about it.
--
-- DDL run in the SQL editor does not always refresh the schema cache, and
-- until it does the API answers "could not find the function" for something
-- that is demonstrably there. That single line has cost this project more time
-- than any bug in it.
-- ---------------------------------------------------------------------------
notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- What is actually present now. Read this output.
-- ---------------------------------------------------------------------------
select
  kind,
  name,
  case when present then 'ok' else 'MISSING' end as state
from (
  select 'table' as kind, t.name,
         exists (select 1 from information_schema.tables
                  where table_schema = 'public' and table_name = t.name) as present
  from (values
    ('site_settings'), ('contact_messages'), ('events'), ('reviews'),
    ('push_subscriptions'), ('live_slides'), ('live_messages'), ('live_board_ops')
  ) as t(name)
  union all
  select 'function', f.name,
         exists (select 1 from pg_proc p
                 join pg_namespace n on n.oid = p.pronamespace
                 where n.nspname = 'public' and p.proname = f.name)
  from (values
    ('admin_generate_coupons'), ('admin_mark_reviewed'), ('unreviewed_student_count'),
    ('admin_grant_entitlement'), ('admin_anonymise_user'), ('rate_limit_hit')
  ) as f(name)
  union all
  select 'column', c.label,
         exists (select 1 from information_schema.columns
                 where table_schema = 'public' and table_name = c.tbl and column_name = c.col)
  from (values
    ('courses.department', 'courses', 'department'),
    ('courses.gallery', 'courses', 'gallery'),
    ('profiles.reviewed_at', 'profiles', 'reviewed_at')
  ) as c(label, tbl, col)
) as checks
order by state desc, kind, name;
FOOTER
